# Generated by Django 3.2.6 on 2021-08-23 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('website', '0002_auto_20210817_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.FileField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
